### ISSUE TITLE
Git Gutter indicators not appearing

### ISSUE THREAD

**Issue by gbarriga** [JachymT/Hololive-EN-VSCode#1]
Big fan of these colors! However it seems [VSCode's git indicators](https://code.visualstudio.com/Docs/editor/versioncontrol#_gutter-indicators) don't show when I have these colors enabled. An example:

VSCode's standard dark theme:
![image](https://user-images.githubusercontent.com/89029150/131149042-402e687c-e09b-48ac-bee2-384e1dc8e371.png)

The same line using Ina's theme:
![image](https://user-images.githubusercontent.com/89029150/131149123-c52623db-9cfb-4ec8-bd34-084564c3f7d8.png)

The same is true for the Gura and Mori theme. I love the colors and would love to keep using them, but this makes it a bit hard to stick with them when working in large files.

**Comment by JachymT** [comment]
Hi Gabriel, thanks so much for getting in touch, I had no idea they
weren't showing up, honestly it's really nice to have some help improving
it.

I'll get on that right away, thanks for the screenshots and i'm really glad
you like the colours <33

**Comment by gbarriga** [comment]
> Hi Gabriel, thanks so much for getting in touch, I had no idea they weren't showing up, honestly it's really nice to have some help improving it. I'll get on that right away, thanks for the screenshots and i'm really glad you like the colours <33

Glad I was able to be of help! If I understood how to test vscode themes, I'd have tried to find a fix and make a PR for it myself, but I figured it'd be faster just making an issue and letting you know directly than start looking up tutorials haha.

Looking forward to the Amelia and Kiara themes!!

**Comment by JachymT** [comment]
Added git indicators for each of the themes with the latest version. Technically its released but I'm waiting to see if i can fix the version numbers first. Thanks again, I'm looking forward to releasing the Ame and Kiara themes soon!
